server:
  port: 8083

spring:
  mqtt:
    username: root
    password: 123456
    url: tcp://远程服务器ip地址:1883
    client:
      id: mqttId
    completionTimeout: 10000
    default:
      topic: topic
    qos: 1
